# Generated by Django 3.2.5 on 2021-10-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='driverLicense',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
