# Generated by Django 3.2.5 on 2021-10-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='provinceId',
            new_name='wardId',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subDistrictId',
        ),
    ]
