# Generated by Django 3.2.5 on 2021-09-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dateOfBirth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
