# Generated by Django 3.2.5 on 2021-11-08 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Processing'), (2, 'Delivering'), (3, 'Delivered'), (4, 'Failed')], default=1)),
                ('paymentMethod', models.IntegerField(choices=[(1, 'Pay by consignor'), (2, 'Pay by consignee')], null=True)),
                ('productPreview', models.IntegerField(choices=[(1, 'Customer not allow to observe products'), (2, 'Customer allow to observe products but not to try them'), (3, 'Customer allow to try products')], null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('estimateDistance', models.FloatField(blank=True, null=True)),
                ('deliverTime', models.FloatField(default=1000)),
                ('shippingPrice', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowerLimit', models.IntegerField(default=0)),
                ('upperLimit', models.IntegerField(default=1000)),
                ('price', models.IntegerField(default=20000)),
            ],
        ),
        migrations.AddConstraint(
            model_name='shipdistance',
            constraint=models.CheckConstraint(check=models.Q(('upperLimit__gt', django.db.models.expressions.F('lowerLimit'))), name='check_valid_limit'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='consignee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='account.profile'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipper', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
