# Generated by Django 3.2.5 on 2021-10-14 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('cnor', 'Consignor'), ('cnee', 'Consignee')], max_length=25)),
                ('fullName', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('provinceId', models.IntegerField(blank=True, null=True)),
                ('districtId', models.IntegerField(blank=True, null=True)),
                ('subDistrictId', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Failed'), (1, 'Processing'), (2, 'Delivering'), (3, 'Delivered')], default=1)),
                ('paymentMethod', models.IntegerField(choices=[(1, 'Pay by consignor'), (2, 'Pay by consignee')], null=True)),
                ('productPreview', models.IntegerField(choices=[(1, 'Customer not allow to observe products'), (2, 'Customer allow to observe products but not to try them'), (3, 'Customer allow to try products')], null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowerLimit', models.IntegerField(blank=True, null=True)),
                ('upperLimit', models.IntegerField(blank=True, default=1000, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='shipdistance',
            constraint=models.CheckConstraint(check=models.Q(('upperLimit__gt', django.db.models.expressions.F('lowerLimit'))), name='check_valid_limit'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='consignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignee', to='order.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='consignor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignor', to='order.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipDistance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.shipdistance'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
