# Generated by Django 3.2.5 on 2021-10-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='consignor',
            new_name='user',
        ),
    ]
