# Generated by Django 3.2.5 on 2021-09-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
