# Generated by Django 3.2.5 on 2021-09-11 12:20

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_delete_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowerLimit', models.IntegerField(blank=True, null=True)),
                ('upperLimit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='shipdistance',
            constraint=models.CheckConstraint(check=models.Q(('upperLimit__gt', django.db.models.expressions.F('lowerLimit'))), name='check_valid_limit'),
        ),
    ]
