# Generated by Django 3.2.5 on 2021-10-14 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211014_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='note',
        ),
    ]
