# Generated by Django 3.2.5 on 2021-10-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211025_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Processing'), (2, 'Delivering'), (3, 'Delivered'), (4, 'Failed')], default=1),
        ),
    ]
