# Generated by Django 3.2.5 on 2021-09-11 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210911_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipDistance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.shipdistance'),
        ),
        migrations.AddField(
            model_name='order',
            name='shippingType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.shippingtype'),
        ),
    ]
