# Generated by Django 3.2.5 on 2021-11-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, default='{"lat":10.0171277,"lon":105.7842959}', max_length=100, null=True),
        ),
    ]
