# Generated by Django 3.2.5 on 2021-10-14 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_productorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='consignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignee', to='order.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='consignor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignor', to='order.customer'),
        ),
    ]
