# Generated by Django 3.2.5 on 2021-09-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210911_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.IntegerField(choices=[(0, 'Pay by consignor'), (1, 'Pay by consignee')], max_length=50, null=True),
        ),
    ]
