# Generated by Django 3.2.5 on 2021-11-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_shipper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipdistance',
            name='lowerLimit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shipdistance',
            name='price',
            field=models.IntegerField(default=20000),
        ),
        migrations.AlterField(
            model_name='shipdistance',
            name='upperLimit',
            field=models.IntegerField(default=1000),
        ),
    ]
