# Generated by Django 3.2.5 on 2021-10-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20211014_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='provinceId',
        ),
    ]
