# Generated by Django 3.2.5 on 2021-09-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipdistance',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.IntegerField(choices=[(0, 'Pay by consignor'), (1, 'Pay by consignee')], null=True),
        ),
    ]
