# Generated by Django 3.2.5 on 2021-09-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210914_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='productPreview',
            field=models.IntegerField(choices=[(0, 'Customer not allow to observe products'), (1, 'Customer allow to observe products but not to try them'), (2, 'Customer allow to try products')], null=True),
        ),
    ]
