# Generated by Django 3.2.5 on 2021-09-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_productpreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Failed'), (1, 'Processing'), (2, 'Delivering'), (3, 'Delivered')], null=True),
        ),
    ]
