# Generated by Django 3.2.5 on 2021-09-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shippingType',
            field=models.IntegerField(choices=[(0, 'Standard'), (1, 'Advanced')], null=True),
        ),
        migrations.DeleteModel(
            name='ShippingType',
        ),
    ]
