# Generated by Django 3.2.5 on 2021-09-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20210919_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Failed'), (1, 'Processing'), (2, 'Delivering'), (3, 'Delivered')], default=1),
        ),
    ]
